// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: notify/v1/notify.proto

package notifyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	PushToken     string                 `protobuf:"bytes,2,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDeviceRequest) Reset() {
	*x = RegisterDeviceRequest{}
	mi := &file_notify_v1_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDeviceRequest) ProtoMessage() {}

func (x *RegisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*RegisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDeviceRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *RegisterDeviceRequest) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

type UnregisterDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PushToken     string                 `protobuf:"bytes,1,opt,name=push_token,json=pushToken,proto3" json:"push_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterDeviceRequest) Reset() {
	*x = UnregisterDeviceRequest{}
	mi := &file_notify_v1_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterDeviceRequest) ProtoMessage() {}

func (x *UnregisterDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notify_v1_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterDeviceRequest.ProtoReflect.Descriptor instead.
func (*UnregisterDeviceRequest) Descriptor() ([]byte, []int) {
	return file_notify_v1_notify_proto_rawDescGZIP(), []int{1}
}

func (x *UnregisterDeviceRequest) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

var File_notify_v1_notify_proto protoreflect.FileDescriptor

const file_notify_v1_notify_proto_rawDesc = "" +
	"\n" +
	"\x16notify/v1/notify.proto\x12\tnotify.v1\x1a\x1bgoogle/protobuf/empty.proto\"R\n" +
	"\x15RegisterDeviceRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x1d\n" +
	"\n" +
	"push_token\x18\x02 \x01(\tR\tpushToken\"8\n" +
	"\x17UnregisterDeviceRequest\x12\x1d\n" +
	"\n" +
	"push_token\x18\x01 \x01(\tR\tpushToken2\xab\x01\n" +
	"\rNotifyService\x12J\n" +
	"\x0eRegisterDevice\x12 .notify.v1.RegisterDeviceRequest\x1a\x16.google.protobuf.Empty\x12N\n" +
	"\x10UnregisterDevice\x12\".notify.v1.UnregisterDeviceRequest\x1a\x16.google.protobuf.EmptyBDZBgithub.com/CARAI-REA/messanger/shared/pkg/proto/notify/v1;notifyv1b\x06proto3"

var (
	file_notify_v1_notify_proto_rawDescOnce sync.Once
	file_notify_v1_notify_proto_rawDescData []byte
)

func file_notify_v1_notify_proto_rawDescGZIP() []byte {
	file_notify_v1_notify_proto_rawDescOnce.Do(func() {
		file_notify_v1_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notify_v1_notify_proto_rawDesc), len(file_notify_v1_notify_proto_rawDesc)))
	})
	return file_notify_v1_notify_proto_rawDescData
}

var file_notify_v1_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notify_v1_notify_proto_goTypes = []any{
	(*RegisterDeviceRequest)(nil),   // 0: notify.v1.RegisterDeviceRequest
	(*UnregisterDeviceRequest)(nil), // 1: notify.v1.UnregisterDeviceRequest
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_notify_v1_notify_proto_depIdxs = []int32{
	0, // 0: notify.v1.NotifyService.RegisterDevice:input_type -> notify.v1.RegisterDeviceRequest
	1, // 1: notify.v1.NotifyService.UnregisterDevice:input_type -> notify.v1.UnregisterDeviceRequest
	2, // 2: notify.v1.NotifyService.RegisterDevice:output_type -> google.protobuf.Empty
	2, // 3: notify.v1.NotifyService.UnregisterDevice:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notify_v1_notify_proto_init() }
func file_notify_v1_notify_proto_init() {
	if File_notify_v1_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notify_v1_notify_proto_rawDesc), len(file_notify_v1_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notify_v1_notify_proto_goTypes,
		DependencyIndexes: file_notify_v1_notify_proto_depIdxs,
		MessageInfos:      file_notify_v1_notify_proto_msgTypes,
	}.Build()
	File_notify_v1_notify_proto = out.File
	file_notify_v1_notify_proto_goTypes = nil
	file_notify_v1_notify_proto_depIdxs = nil
}
