FROM golang:1.25-alpine AS builder
WORKDIR /src
RUN apk add --no-cache ca-certificates
COPY platform ./platform
COPY shared ./shared
COPY media ./media
WORKDIR /src/media
RUN CGO_ENABLED=0 go build -mod=vendor -o /out/media ./cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/media /app/bin/media
COPY media/internal/migrations /app/internal/migrations
ENV MIGRATION_DIRECTORY=/app/internal/migrations
EXPOSE 50053 9105
ENTRYPOINT ["/app/bin/media"]
