FROM golang:1.25-alpine AS builder
WORKDIR /src
RUN apk add --no-cache ca-certificates
COPY platform ./platform
COPY shared ./shared
COPY user ./user
WORKDIR /src/user
RUN CGO_ENABLED=0 go build -mod=vendor -o /out/user ./cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/user /app/bin/user
COPY user/internal/migrations /app/internal/migrations
ENV MIGRATION_DIRECTORY=/app/internal/migrations
EXPOSE 50051 9101
ENTRYPOINT ["/app/bin/user"]
