FROM golang:1.25-alpine AS builder
WORKDIR /src
RUN apk add --no-cache ca-certificates
COPY platform ./platform
COPY shared ./shared
COPY search ./search
WORKDIR /src/search
RUN CGO_ENABLED=0 go build -mod=vendor -o /out/search ./cmd

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/search /app/bin/search
EXPOSE 50054 9106
ENTRYPOINT ["/app/bin/search"]
