apiVersion: v1
kind: Namespace
metadata:
  name: messanger
---
apiVersion: v1
kind: Secret
metadata:
  name: messanger-secrets
  namespace: messanger
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_ACCESS"
  REFRESH_TOKEN_SECRET: "CHANGE_ME_REFRESH"
  SERVICE_JWT_SECRET: "CHANGE_ME_SERVICE"
  POSTGRES_PASSWORD: "CHANGE_ME"
  REDIS_PASSWORD: "CHANGE_ME_REDIS"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: messanger-config
  namespace: messanger
data:
  APP_ENV: "production"
  LOGGER_LEVEL: "info"
  LOGGER_AS_JSON: "true"
  POSTGRES_SSL_MODE: "require"
  REALTIME_CHANNEL: "chat:realtime"
  KAFKA_CHAT_EVENTS_TOPIC: "chat.events"
