// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: events/v1/events.proto

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreated) Reset() {
	*x = UserCreated{}
	mi := &file_events_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreated) ProtoMessage() {}

func (x *UserCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreated.ProtoReflect.Descriptor instead.
func (*UserCreated) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserCreated) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type UserDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleted) Reset() {
	*x = UserDeleted{}
	mi := &file_events_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleted) ProtoMessage() {}

func (x *UserDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleted.ProtoReflect.Descriptor instead.
func (*UserDeleted) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserDeleted) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDeleted) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type ChatRealtimeEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ChatId  int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ActorId int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	At      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatRealtimeEvent_MessageCreated
	//	*ChatRealtimeEvent_MessageEdited
	//	*ChatRealtimeEvent_MessageDeleted
	//	*ChatRealtimeEvent_MessagePinned
	//	*ChatRealtimeEvent_ReceiptRead
	//	*ChatRealtimeEvent_MemberChanged
	Payload       isChatRealtimeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRealtimeEvent) Reset() {
	*x = ChatRealtimeEvent{}
	mi := &file_events_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRealtimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRealtimeEvent) ProtoMessage() {}

func (x *ChatRealtimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRealtimeEvent.ProtoReflect.Descriptor instead.
func (*ChatRealtimeEvent) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *ChatRealtimeEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ChatRealtimeEvent) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChatRealtimeEvent) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *ChatRealtimeEvent) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *ChatRealtimeEvent) GetPayload() isChatRealtimeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatRealtimeEvent) GetMessageCreated() *MessageCreated {
	if x != nil {
		if x, ok := x.Payload.(*ChatRealtimeEvent_MessageCreated); ok {
			return x.MessageCreated
		}
	}
	return nil
}

func (x *ChatRealtimeEvent) GetMessageEdited() *MessageEdited {
	if x != nil {
		if x, ok := x.Payload.(*ChatRealtimeEvent_MessageEdited); ok {
			return x.MessageEdited
		}
	}
	return nil
}

func (x *ChatRealtimeEvent) GetMessageDeleted() *MessageDeleted {
	if x != nil {
		if x, ok := x.Payload.(*ChatRealtimeEvent_MessageDeleted); ok {
			return x.MessageDeleted
		}
	}
	return nil
}

func (x *ChatRealtimeEvent) GetMessagePinned() *MessagePinned {
	if x != nil {
		if x, ok := x.Payload.(*ChatRealtimeEvent_MessagePinned); ok {
			return x.MessagePinned
		}
	}
	return nil
}

func (x *ChatRealtimeEvent) GetReceiptRead() *ReceiptRead {
	if x != nil {
		if x, ok := x.Payload.(*ChatRealtimeEvent_ReceiptRead); ok {
			return x.ReceiptRead
		}
	}
	return nil
}

func (x *ChatRealtimeEvent) GetMemberChanged() *MemberChanged {
	if x != nil {
		if x, ok := x.Payload.(*ChatRealtimeEvent_MemberChanged); ok {
			return x.MemberChanged
		}
	}
	return nil
}

type isChatRealtimeEvent_Payload interface {
	isChatRealtimeEvent_Payload()
}

type ChatRealtimeEvent_MessageCreated struct {
	MessageCreated *MessageCreated `protobuf:"bytes,10,opt,name=message_created,json=messageCreated,proto3,oneof"`
}

type ChatRealtimeEvent_MessageEdited struct {
	MessageEdited *MessageEdited `protobuf:"bytes,11,opt,name=message_edited,json=messageEdited,proto3,oneof"`
}

type ChatRealtimeEvent_MessageDeleted struct {
	MessageDeleted *MessageDeleted `protobuf:"bytes,12,opt,name=message_deleted,json=messageDeleted,proto3,oneof"`
}

type ChatRealtimeEvent_MessagePinned struct {
	MessagePinned *MessagePinned `protobuf:"bytes,13,opt,name=message_pinned,json=messagePinned,proto3,oneof"`
}

type ChatRealtimeEvent_ReceiptRead struct {
	ReceiptRead *ReceiptRead `protobuf:"bytes,14,opt,name=receipt_read,json=receiptRead,proto3,oneof"`
}

type ChatRealtimeEvent_MemberChanged struct {
	MemberChanged *MemberChanged `protobuf:"bytes,15,opt,name=member_changed,json=memberChanged,proto3,oneof"`
}

func (*ChatRealtimeEvent_MessageCreated) isChatRealtimeEvent_Payload() {}

func (*ChatRealtimeEvent_MessageEdited) isChatRealtimeEvent_Payload() {}

func (*ChatRealtimeEvent_MessageDeleted) isChatRealtimeEvent_Payload() {}

func (*ChatRealtimeEvent_MessagePinned) isChatRealtimeEvent_Payload() {}

func (*ChatRealtimeEvent_ReceiptRead) isChatRealtimeEvent_Payload() {}

func (*ChatRealtimeEvent_MemberChanged) isChatRealtimeEvent_Payload() {}

type MessageCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	AttachmentIds []string               `protobuf:"bytes,4,rep,name=attachment_ids,json=attachmentIds,proto3" json:"attachment_ids,omitempty"`
	SendAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageCreated) Reset() {
	*x = MessageCreated{}
	mi := &file_events_v1_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCreated) ProtoMessage() {}

func (x *MessageCreated) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCreated.ProtoReflect.Descriptor instead.
func (*MessageCreated) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{3}
}

func (x *MessageCreated) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageCreated) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *MessageCreated) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageCreated) GetAttachmentIds() []string {
	if x != nil {
		return x.AttachmentIds
	}
	return nil
}

func (x *MessageCreated) GetSendAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SendAt
	}
	return nil
}

type MessageEdited struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEdited) Reset() {
	*x = MessageEdited{}
	mi := &file_events_v1_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEdited) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEdited) ProtoMessage() {}

func (x *MessageEdited) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEdited.ProtoReflect.Descriptor instead.
func (*MessageEdited) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{4}
}

func (x *MessageEdited) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageEdited) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageEdited) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type MessageDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeleted) Reset() {
	*x = MessageDeleted{}
	mi := &file_events_v1_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeleted) ProtoMessage() {}

func (x *MessageDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeleted.ProtoReflect.Descriptor instead.
func (*MessageDeleted) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{5}
}

func (x *MessageDeleted) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type MessagePinned struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IsPinned      bool                   `protobuf:"varint,2,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagePinned) Reset() {
	*x = MessagePinned{}
	mi := &file_events_v1_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePinned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePinned) ProtoMessage() {}

func (x *MessagePinned) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePinned.ProtoReflect.Descriptor instead.
func (*MessagePinned) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{6}
}

func (x *MessagePinned) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessagePinned) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

type ReceiptRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceiptRead) Reset() {
	*x = ReceiptRead{}
	mi := &file_events_v1_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceiptRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptRead) ProtoMessage() {}

func (x *ReceiptRead) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptRead.ProtoReflect.Descriptor instead.
func (*ReceiptRead) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{7}
}

func (x *ReceiptRead) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReceiptRead) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type MemberChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Role          int32                  `protobuf:"varint,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberChanged) Reset() {
	*x = MemberChanged{}
	mi := &file_events_v1_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberChanged) ProtoMessage() {}

func (x *MemberChanged) ProtoReflect() protoreflect.Message {
	mi := &file_events_v1_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberChanged.ProtoReflect.Descriptor instead.
func (*MemberChanged) Descriptor() ([]byte, []int) {
	return file_events_v1_events_proto_rawDescGZIP(), []int{8}
}

func (x *MemberChanged) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberChanged) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MemberChanged) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

var File_events_v1_events_proto protoreflect.FileDescriptor

const file_events_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16events/v1/events.proto\x12\tevents.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n" +
	"\vUserCreated\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"a\n" +
	"\vUserDeleted\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x129\n" +
	"\n" +
	"deleted_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xab\x04\n" +
	"\x11ChatRealtimeEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12*\n" +
	"\x02at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12D\n" +
	"\x0fmessage_created\x18\n" +
	" \x01(\v2\x19.events.v1.MessageCreatedH\x00R\x0emessageCreated\x12A\n" +
	"\x0emessage_edited\x18\v \x01(\v2\x18.events.v1.MessageEditedH\x00R\rmessageEdited\x12D\n" +
	"\x0fmessage_deleted\x18\f \x01(\v2\x19.events.v1.MessageDeletedH\x00R\x0emessageDeleted\x12A\n" +
	"\x0emessage_pinned\x18\r \x01(\v2\x18.events.v1.MessagePinnedH\x00R\rmessagePinned\x12;\n" +
	"\freceipt_read\x18\x0e \x01(\v2\x16.events.v1.ReceiptReadH\x00R\vreceiptRead\x12A\n" +
	"\x0emember_changed\x18\x0f \x01(\v2\x18.events.v1.MemberChangedH\x00R\rmemberChangedB\t\n" +
	"\apayload\"\xbc\x01\n" +
	"\x0eMessageCreated\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12%\n" +
	"\x0eattachment_ids\x18\x04 \x03(\tR\rattachmentIds\x123\n" +
	"\asend_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06sendAt\"}\n" +
	"\rMessageEdited\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"/\n" +
	"\x0eMessageDeleted\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"K\n" +
	"\rMessagePinned\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1b\n" +
	"\tis_pinned\x18\x02 \x01(\bR\bisPinned\"E\n" +
	"\vReceiptRead\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\"T\n" +
	"\rMemberChanged\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x12\n" +
	"\x04role\x18\x03 \x01(\x05R\x04roleBDZBgithub.com/CARAI-REA/messanger/shared/pkg/proto/events/v1;eventsv1b\x06proto3"

var (
	file_events_v1_events_proto_rawDescOnce sync.Once
	file_events_v1_events_proto_rawDescData []byte
)

func file_events_v1_events_proto_rawDescGZIP() []byte {
	file_events_v1_events_proto_rawDescOnce.Do(func() {
		file_events_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_v1_events_proto_rawDesc), len(file_events_v1_events_proto_rawDesc)))
	})
	return file_events_v1_events_proto_rawDescData
}

var file_events_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_events_v1_events_proto_goTypes = []any{
	(*UserCreated)(nil),           // 0: events.v1.UserCreated
	(*UserDeleted)(nil),           // 1: events.v1.UserDeleted
	(*ChatRealtimeEvent)(nil),     // 2: events.v1.ChatRealtimeEvent
	(*MessageCreated)(nil),        // 3: events.v1.MessageCreated
	(*MessageEdited)(nil),         // 4: events.v1.MessageEdited
	(*MessageDeleted)(nil),        // 5: events.v1.MessageDeleted
	(*MessagePinned)(nil),         // 6: events.v1.MessagePinned
	(*ReceiptRead)(nil),           // 7: events.v1.ReceiptRead
	(*MemberChanged)(nil),         // 8: events.v1.MemberChanged
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_events_v1_events_proto_depIdxs = []int32{
	9,  // 0: events.v1.UserCreated.created_at:type_name -> google.protobuf.Timestamp
	9,  // 1: events.v1.UserDeleted.deleted_at:type_name -> google.protobuf.Timestamp
	9,  // 2: events.v1.ChatRealtimeEvent.at:type_name -> google.protobuf.Timestamp
	3,  // 3: events.v1.ChatRealtimeEvent.message_created:type_name -> events.v1.MessageCreated
	4,  // 4: events.v1.ChatRealtimeEvent.message_edited:type_name -> events.v1.MessageEdited
	5,  // 5: events.v1.ChatRealtimeEvent.message_deleted:type_name -> events.v1.MessageDeleted
	6,  // 6: events.v1.ChatRealtimeEvent.message_pinned:type_name -> events.v1.MessagePinned
	7,  // 7: events.v1.ChatRealtimeEvent.receipt_read:type_name -> events.v1.ReceiptRead
	8,  // 8: events.v1.ChatRealtimeEvent.member_changed:type_name -> events.v1.MemberChanged
	9,  // 9: events.v1.MessageCreated.send_at:type_name -> google.protobuf.Timestamp
	9,  // 10: events.v1.MessageEdited.updated_at:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_events_v1_events_proto_init() }
func file_events_v1_events_proto_init() {
	if File_events_v1_events_proto != nil {
		return
	}
	file_events_v1_events_proto_msgTypes[2].OneofWrappers = []any{
		(*ChatRealtimeEvent_MessageCreated)(nil),
		(*ChatRealtimeEvent_MessageEdited)(nil),
		(*ChatRealtimeEvent_MessageDeleted)(nil),
		(*ChatRealtimeEvent_MessagePinned)(nil),
		(*ChatRealtimeEvent_ReceiptRead)(nil),
		(*ChatRealtimeEvent_MemberChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_v1_events_proto_rawDesc), len(file_events_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_v1_events_proto_goTypes,
		DependencyIndexes: file_events_v1_events_proto_depIdxs,
		MessageInfos:      file_events_v1_events_proto_msgTypes,
	}.Build()
	File_events_v1_events_proto = out.File
	file_events_v1_events_proto_goTypes = nil
	file_events_v1_events_proto_depIdxs = nil
}
