// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: search/v1/search.proto

package searchv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesRequest) Reset() {
	*x = SearchMessagesRequest{}
	mi := &file_search_v1_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesRequest) ProtoMessage() {}

func (x *SearchMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesRequest.ProtoReflect.Descriptor instead.
func (*SearchMessagesRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchMessagesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SearchMessagesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchMessageHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessageHit) Reset() {
	*x = SearchMessageHit{}
	mi := &file_search_v1_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessageHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessageHit) ProtoMessage() {}

func (x *SearchMessageHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessageHit.ProtoReflect.Descriptor instead.
func (*SearchMessageHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchMessageHit) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *SearchMessageHit) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SearchMessageHit) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SearchMessageHit) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SearchMessageHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchMessageHit    `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMessagesResponse) Reset() {
	*x = SearchMessagesResponse{}
	mi := &file_search_v1_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMessagesResponse) ProtoMessage() {}

func (x *SearchMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMessagesResponse.ProtoReflect.Descriptor instead.
func (*SearchMessagesResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchMessagesResponse) GetHits() []*SearchMessageHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchMessagesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type SearchChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsRequest) Reset() {
	*x = SearchChatsRequest{}
	mi := &file_search_v1_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsRequest) ProtoMessage() {}

func (x *SearchChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsRequest.ProtoReflect.Descriptor instead.
func (*SearchChatsRequest) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchChatsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchChatsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchChatHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatHit) Reset() {
	*x = SearchChatHit{}
	mi := &file_search_v1_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatHit) ProtoMessage() {}

func (x *SearchChatHit) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatHit.ProtoReflect.Descriptor instead.
func (*SearchChatHit) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchChatHit) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SearchChatHit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchChatHit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchChatHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchChatHit       `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchChatsResponse) Reset() {
	*x = SearchChatsResponse{}
	mi := &file_search_v1_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchChatsResponse) ProtoMessage() {}

func (x *SearchChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_v1_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchChatsResponse.ProtoReflect.Descriptor instead.
func (*SearchChatsResponse) Descriptor() ([]byte, []int) {
	return file_search_v1_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchChatsResponse) GetHits() []*SearchChatHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

func (x *SearchChatsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_search_v1_search_proto protoreflect.FileDescriptor

const file_search_v1_search_proto_rawDesc = "" +
	"\n" +
	"\x16search/v1/search.proto\x12\tsearch.v1\x1a\x1cgoogle/api/annotations.proto\"t\n" +
	"\x15SearchMessagesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x91\x01\n" +
	"\x10SearchMessageHit\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\"j\n" +
	"\x16SearchMessagesResponse\x12/\n" +
	"\x04hits\x18\x01 \x03(\v2\x1b.search.v1.SearchMessageHitR\x04hits\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"X\n" +
	"\x12SearchChatsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"t\n" +
	"\rSearchChatHit\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"d\n" +
	"\x13SearchChatsResponse\x12,\n" +
	"\x04hits\x18\x01 \x03(\v2\x18.search.v1.SearchChatHitR\x04hits\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xf3\x01\n" +
	"\rSearchService\x12v\n" +
	"\x0eSearchMessages\x12 .search.v1.SearchMessagesRequest\x1a!.search.v1.SearchMessagesResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/search/messages\x12j\n" +
	"\vSearchChats\x12\x1d.search.v1.SearchChatsRequest\x1a\x1e.search.v1.SearchChatsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/search/chatsBDZBgithub.com/CARAI-REA/messanger/shared/pkg/proto/search/v1;searchv1b\x06proto3"

var (
	file_search_v1_search_proto_rawDescOnce sync.Once
	file_search_v1_search_proto_rawDescData []byte
)

func file_search_v1_search_proto_rawDescGZIP() []byte {
	file_search_v1_search_proto_rawDescOnce.Do(func() {
		file_search_v1_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)))
	})
	return file_search_v1_search_proto_rawDescData
}

var file_search_v1_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_search_v1_search_proto_goTypes = []any{
	(*SearchMessagesRequest)(nil),  // 0: search.v1.SearchMessagesRequest
	(*SearchMessageHit)(nil),       // 1: search.v1.SearchMessageHit
	(*SearchMessagesResponse)(nil), // 2: search.v1.SearchMessagesResponse
	(*SearchChatsRequest)(nil),     // 3: search.v1.SearchChatsRequest
	(*SearchChatHit)(nil),          // 4: search.v1.SearchChatHit
	(*SearchChatsResponse)(nil),    // 5: search.v1.SearchChatsResponse
}
var file_search_v1_search_proto_depIdxs = []int32{
	1, // 0: search.v1.SearchMessagesResponse.hits:type_name -> search.v1.SearchMessageHit
	4, // 1: search.v1.SearchChatsResponse.hits:type_name -> search.v1.SearchChatHit
	0, // 2: search.v1.SearchService.SearchMessages:input_type -> search.v1.SearchMessagesRequest
	3, // 3: search.v1.SearchService.SearchChats:input_type -> search.v1.SearchChatsRequest
	2, // 4: search.v1.SearchService.SearchMessages:output_type -> search.v1.SearchMessagesResponse
	5, // 5: search.v1.SearchService.SearchChats:output_type -> search.v1.SearchChatsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_search_v1_search_proto_init() }
func file_search_v1_search_proto_init() {
	if File_search_v1_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_v1_search_proto_rawDesc), len(file_search_v1_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_v1_search_proto_goTypes,
		DependencyIndexes: file_search_v1_search_proto_depIdxs,
		MessageInfos:      file_search_v1_search_proto_msgTypes,
	}.Build()
	File_search_v1_search_proto = out.File
	file_search_v1_search_proto_goTypes = nil
	file_search_v1_search_proto_depIdxs = nil
}
